---

- name: Deploy Image
  docker_container:
    name: flask
    image: johnmops/python-app:{{ experimentVersion }}
    state: started
    restart: yes
    ports:
     - "80:80"
     

- name: Check that a page returns a status 200 and fail if 'Hello World' is not in the page contents
  uri:
    url: http://{{ hostIP }}
    return_content: yes
  register: out
  failed_when: "'Hello World' not in out.content"
  
  
